from turtle import *
speed(100)
def rhombus_3(x,y,a):
    color('black')
    fillcolor('red')
    begin_fill()
    up()
    setposition(x,y)
    down()
    left(120)
    forward(a)
    right(60)
    forward(a)
    right(120)
    forward(a)
    right(60)
    forward(a)
    left(120)
    end_fill()

def triangle_7(x,y,a):
    color('black')
    fillcolor('pink')
    begin_fill()
    up()
    setposition(x, y)
    down()
    forward(a)
    right(120)
    forward(a)
    right(120)
    forward(a)
    right(120)
    end_fill()

def triangle_6(x,y,a):
    color('black')
    fillcolor('navy')
    begin_fill()
    up()
    setposition(x,y)
    down()
    left(60)
    forward(a)
    right(120)
    forward(a)
    right(120)
    forward(a)
    right(180)
    end_fill()

def square_2(x, y, a):
    color('black')
    fillcolor('purple')
    begin_fill()
    up()
    setposition(x, y)
    down()
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    end_fill()

def square_1 (x, y, a):
    color('black')
    fillcolor('green')
    begin_fill()
    up()
    setposition(x, y)
    down()
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    end_fill()

def parallelogram_4 (x, y, a, b):
    color('black')
    fillcolor('yellow')
    begin_fill()
    up()
    setposition(x, y)
    down()
    left(180)
    forward(a)
    right(60)
    forward(b)
    right(120)
    forward(a)
    right(60)
    forward(b)
    left(60)
    end_fill()

def triangle_5 (x, y, a):
    color('black')
    fillcolor('orange')
    begin_fill()
    up()
    setposition(x, y)
    down()
    forward(a)
    left(120)
    forward(a)
    left(120)
    forward(a)
    right(240)
    end_fill()

def platypus():
    rhombus_3(-400,100,130)
    left(150)
    square_1(-400,100,40)
    left(60)
    square_2(-435,80,40)
    left(30)
    triangle_5(-400,100,50)
    left(60)
    triangle_6(-400,325,70)
    right(60)
    triangle_7(-400,325,70)
    left(30)
    parallelogram_4(-400,325,50,30)
    up()
    color('black')
    home()
    down()

def crab_Sasha():
    left(90)
    rhombus_3(-20,250,130)
    left(60)
    triangle_6(-134, 185, 70)
    right(120)
    triangle_7(-133, 185, 70)
    right(90)
    square_2(-135, 314, 40)
    left(30)
    square_1(-75,328,40)
    right(180)
    triangle_5(-245,250,50)
    left(120)
    parallelogram_4(-287,275,50,30)
    up()
    color('black')
    home()
    down()

def rhombus_body_robot(x,y,a):
    color('black')
    fillcolor('red')
    begin_fill()
    up()
    setposition(x,y)
    down()
    left(120)
    forward(a)
    right(60)
    forward(a)
    right(120)
    forward(a)
    right(60)
    forward(a)
    left(120)
    end_fill()

def triangle_head_lower_robot(x,y,a):
    color('black')
    fillcolor('pink')
    begin_fill()
    up()
    setposition(x, y)
    down()
    forward(a)
    right(120)
    forward(a)
    right(120)
    forward(a)
    right(120)
    end_fill()

def triangle_head_upper_robot(x,y,a):
    color('black')
    fillcolor('navy')
    begin_fill()
    up()
    setposition(x,y)
    down()
    left(60)
    forward(a)
    right(120)
    forward(a)
    right(120)
    forward(a)
    right(180)
    end_fill()

def square_ear_right_robot (x, y, a):
    color('black')
    fillcolor('purple')
    begin_fill()
    up()
    setposition(x, y)
    down()
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    end_fill()

def square_ear_left_robot (x, y, a):
    color('black')
    fillcolor('green')
    begin_fill()
    up()
    setposition(x, y)
    down()
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    end_fill()

def parallelogram_hand_left_robot (x, y, a, b):
    color('black')
    fillcolor('yellow')
    begin_fill()
    up()
    setposition(x, y)
    down()
    left(180)
    forward(a)
    right(60)
    forward(b)
    right(120)
    forward(a)
    right(60)
    forward(b)
    left(60)
    end_fill()

def triangle_hand_right_robot (x, y, a):
    color('black')
    fillcolor('orange')
    begin_fill()
    up()
    setposition(x, y)
    down()
    forward(a)
    left(120)
    forward(a)
    left(120)
    forward(a)
    right(240)
    end_fill()

def rhombus_body_turtle(x,y,a):
    color('black')
    fillcolor('red')
    begin_fill()
    up()
    setposition(x,y)
    down()
    left(30)
    forward(a)
    right(60)
    forward(a)
    right(120)
    forward(a)
    right(60)
    forward(a)
    right(150)
    end_fill()

def triangle_fin_left_turtle(x,y,a):
    color('black')
    fillcolor('navy')
    begin_fill()
    up()
    setposition(x,y)
    down()
    left(60)
    forward(a)
    right(120)
    forward(a)
    right(120)
    forward(a)
    right(180)
    end_fill()

def triangle_fin_right_turtle (x,y,a):
    color('black')
    fillcolor('pink')
    begin_fill()
    up()
    setposition(x, y)
    down()
    forward(a)
    right(120)
    forward(a)
    right(120)
    forward(a)
    right(120)
    end_fill()

def square_leg_left_turtle(x, y, a):
    color('black')
    fillcolor('purple')
    begin_fill()
    up()
    setposition(x, y)
    down()
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    end_fill()

def square_leg_right_turtle(x, y, a):
    color('black')
    fillcolor('green')
    begin_fill()
    up()
    setposition(x, y)
    down()
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    end_fill()

def triangle_head_turtle (x, y, a):
    color('black')
    fillcolor('orange')
    begin_fill()
    up()
    setposition(x, y)
    down()
    left(30)
    forward(a)
    right(120)
    forward(a)
    right(120)
    forward(a)
    right(150)
    end_fill()

def parallelogram_tail_turtle (x, y, a, b):
    color('black')
    fillcolor('yellow')
    begin_fill()
    up()
    setposition(x, y)
    down()
    left(180)
    forward(a)
    right(60)
    forward(b)
    right(120)
    forward(a)
    right(60)
    forward(b)
    left(60)
    end_fill()

def rhombus_body_penguin(x,y,a):
    color('black')
    fillcolor('red')
    begin_fill()
    up()
    setposition(x,y)
    down()
    left(120)
    forward(a)
    right(60)
    forward(a)
    right(120)
    forward(a)
    right(60)
    forward(a)
    left(120)
    end_fill()

def parallelogram_head_penguin (x, y, a, b):
    color('black')
    fillcolor('yellow')
    begin_fill()
    up()
    setposition(x, y)
    down()
    left(180)
    forward(a)
    right(60)
    forward(b)
    right(120)
    forward(a)
    right(60)
    forward(b)
    left(60)
    end_fill()

def triangle_hand_left_penguin(x,y,a):
    color('black')
    fillcolor('navy')
    begin_fill()
    up()
    setposition(x,y)
    down()
    left(60)
    forward(a)
    right(120)
    forward(a)
    right(120)
    forward(a)
    right(180)
    end_fill()

def triangle_hand_right_penguin(x,y,a):
    color('black')
    fillcolor('pink')
    begin_fill()
    up()
    setposition(x,y)
    down()
    left(60)
    forward(a)
    right(120)
    forward(a)
    right(120)
    forward(a)
    right(180)
    end_fill()

def triangle_tail_penguin (x, y, a):
    color('black')
    fillcolor('orange')
    begin_fill()
    up()
    setposition(x, y)
    down()
    left(30)
    forward(a)
    right(120)
    forward(a)
    right(120)
    forward(a)
    right(150)
    end_fill()

def square_leg_left_penguin (x, y, a):
    color('black')
    fillcolor('green')
    begin_fill()
    up()
    setposition(x, y)
    down()
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    end_fill()

def square_leg_right_penguin (x, y, a):
    color('black')
    fillcolor('purple')
    begin_fill()
    up()
    setposition(x, y)
    down()
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    right(90)
    forward(a)
    end_fill()

def penguin ():
    rhombus_body_penguin(486, -230, 130)
    parallelogram_head_penguin(511, -5, 50, 30)
    triangle_hand_left_penguin(351, -117, 70)
    triangle_hand_right_penguin(551, -117, 70)
    triangle_tail_penguin(519, -173, 50)
    square_leg_left_penguin(470, -202, 40)
    square_leg_right_penguin(542, -202, 40)

def turtle ():
    rhombus_body_turtle(400, 200, 130)
    triangle_fin_left_turtle(478, 266, 70 )
    triangle_fin_right_turtle(478, 134, 70)
    square_leg_left_turtle(456, 273, 40)
    square_leg_right_turtle(456, 167, 40)
    triangle_head_turtle(624, 200, 50)
    parallelogram_tail_turtle(400,200, 50, 30)

def robot ():
    rhombus_body_robot(135,33,130)
    triangle_head_lower_robot(100, 320, 70)
    triangle_head_upper_robot(100, 320, 70)
    square_ear_right_robot(210, 340, 40)
    square_ear_left_robot(100, 340, 40)
    parallelogram_hand_left_robot(102,201,50, 30)
    triangle_hand_right_robot(168, 201,50)

def rhombus_revers(x, y, a):
    color('black') 
    fillcolor('red') 
    begin_fill() 
    up() 
    setposition(x, y) 
    down() 
    left(30)  
    forward(a) 
    right(60) 
    forward(a) 
    right(120) 
    forward(a) 
    right(60) 
    forward(a)
    right(150)  
    end_fill()

def triangle_6_revers(x, y, a):
    color('black')
    fillcolor('navy')
    begin_fill()
    up()
    setposition(x, y)
    down()
    forward(a)
    right(120)
    forward(a)
    right(120)
    forward(a)
    right(120)
    end_fill()

def rocket():
    rhombus_3(170, -270, 130)
    triangle_5(145, -308, 50)
    parallelogram_4(210, -335, 50, 30)
    triangle_6(200, -220, 70)
    triangle_7(200, -100, 70)
    square_1(190, -10, 40)
    square_2(190, 30, 40)

def person():
    parallelogram_4(-140, 15, 30, 50)
    triangle_5(-180,-30,50)
    rhombus_3(-155,-255, 130)
    triangle_6(-95, -152, 70)
    triangle_7(-280, -127, 70)
    square_1(-163,-245,40)
    square_2(-108,-245,40)

def crab():
    rhombus_revers(-700,-150, 130)
    triangle_6_revers(-767,-147,70)
    triangle_7(-476,-147,70)
    square_1(-519,-200,40)
    square_2(-612,-200,40)
    triangle_5(-610, -85, 50)
    parallelogram_4(-565,-45,30,50)

def main():
    platypus()
    crab_Sasha()
    robot()
    turtle()
    penguin()
    person()
    rocket()
    crab()
    done()
main()